apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: hasn-ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi


