apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasn-api
  namespace: hasn-ai
  labels:
    app: hasn-api
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hasn-api
  template:
    metadata:
      labels:
        app: hasn-api
        version: v1.0.0
    spec:
      containers:
      - name: hasn-api
        image: hasn-ai:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: hasn-config
        - secretRef:
            name: hasn-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: hasn-data-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: hasn-logs-pvc
