apiVersion: v1
kind: Service
metadata:
  name: hasn-api-service
  namespace: hasn-ai
  labels:
    app: hasn-api
spec:
  selector:
    app: hasn-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: hasn-ai
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hasn-ingress
  namespace: hasn-ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - api.hasn-ai.com
    secretName: hasn-tls
  rules:
  - host: api.hasn-ai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hasn-api-service
            port:
              number: 80
