name: Validation and Testing

on:
  push:
    branches: [ '**' ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install black ruff
          black --check src/ examples/ *.py
          ruff check src/ examples/ *.py

      - name: Run tests
        run: |
          pip install pytest pytest-asyncio pytest-cov
          python -m pytest src/tests/ -v

      - name: Trivy FS scan (repo)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
          severity: CRITICAL,HIGH,MEDIUM

      - name: Upload Trivy FS scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs